In [51]:
# Dan Blanchette
# KNN Practice

import numpy as np
from sklearn import datasets as ds # only imports some modules from sklearn. good because whole module may be too large
from sklearn.model_selection import train_test_split # split dataset into train and test sets

# data preparation
iris = ds.load_iris() #loading dataset on iris stuff
X = iris.data # feature vectors ie data
y = iris.target # classification of feature vectors in number format

print(X.shape, y.shape) # will give size of each vector
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2) # splits data set into a training set and test set
                                                                        # with corresponding target vectors

print(f"training set: {X_train.shape}, {y_train.shape}")
print(f"test set: {X_test.shape}, {y_test.shape}")

(150, 4) (150,)
training set: (120, 4), (120,)
test set: (30, 4), (30,)


In [52]:
# 2. Model training
# KNN is an instance-based algorithm, and 
# it does not have the actual training


In [53]:
# 3. Prediction and evaluation
# evaluation metric: error rate : % of data samples missclassified
def predict(X_input):
    ''' X_in: new datta samples. n*4'''
    
    for x in X_in:
        k_inx = findKN

# prediction: 1) find the K nearest neighbors; 2)voting to predict

In [71]:
def findKnNbs(x_star, X_train, K=5):
    """find K nearest neighbors for sample in the training set

    :param x_star: new data sample. Shape 1 by 4
    :param X_train: _description_

    return:
        K nearest neighbors' indeces
    """
    # calculate euclidean distance
    n = X_train.shape[0]
    dist = np.zeros((n,1)) # create numpy array of size n and init all val with 0
    
    index = 0
    for x in X_train:
        # d = ((x_star-x)*(x_star-x)).sum() # element wise multiplication
        d = np.sqrt(np.sum((x_star-x)*(x_star-x)))
        # d = np.sqrt(np.sum((x_star-x) ** 2))
        dist[index] = d
        index += 1
    
    # find k nearest neighbors using a sorting algo
    # numpy has sort!
    # print(dist)
    ind = np.argsort(dist, axis=0)
    # print(ind)
    # print(ind[:K]) # this slices up to the Kth element
    return ind[:K]

k_inx = findKnNbs(X_test[0], X_train)
print(k_inx, "\n")

def findKnNbs2(x_star, X_train, K=7):
    """find K nearest neighbors for sample in the training set

    :param x_star: new data sample. Shape 1 by 4
    :param X_train: _description_

    return:
        K nearest neighbors' indeces
    """
    # calculate euclidean distance
    n = X_train.shape[0]
    dist = np.zeros((n,1)) # create numpy array of size n and init all val with 0
    
    index = 0
    for x in X_train:
        # d = ((x_star-x)*(x_star-x)).sum() # element wise multiplication
        d = np.sqrt(np.sum((x_star-x)*(x_star-x)))
        # d = np.sqrt(np.sum((x_star-x) ** 2))
        dist[index] = d
        index += 1
    
    # find k nearest neighbors using a sorting algo
    # numpy has sort!
    # print(dist)
    ind = np.argsort(dist, axis=0)
    # print(ind)
    # print(ind[:K]) # this slices up to the Kth element
    return ind[:K]

k_inx = findKnNbs2(X_test[0], X_train)
print(k_inx, "\n")
    

[[31]
 [83]
 [75]
 [62]
 [27]] 

[[31]
 [83]] 



In [55]:
# how to find euclidean distance
"""QUESTION
how does this translate to our samples? we're subtracting flower width, adding it to flower petal height, etc

is this how we should graph it then also?
"""
x_star = X_test[0]
print(x_star)

x = X_train[0]
print(x)

np.sqrt(np.sum((x_star - x) ** 2))

[6.7 3.1 4.7 1.5]
[6.2 3.4 5.4 2.3]


1.212435565298214

In [76]:
# afterclass practice
#1. how do we calculate the predictions for all test data samples

test_pred = np.zeros(X_test.shape[0])
index = 0
for i in X_test:
    ind = findKnNbs(i, X_train)

    i_labels = y_train[ind]
    counts = np.bincount(i_labels.reshape((5,)))
    y_pred = np.argmax(counts)
    test_pred[index] = y_pred

    index += 1

# 2. calculate the error rate on the test set

test_err = (test_pred != y_test).sum()/y_test.shape[0]
print(test_err)
# try to use differnt K


test_pred2 = np.zeros(X_test.shape[0])
index2 = 0
for i in X_test:
    ind2 = findKnNbs2(i, X_train)

    i_labels2 = y_train[ind2]
    counts2 = np.bincount(i_labels2.reshape((2,)))
    y_pred2 = np.argmax(counts2)
    test_pred[index2] = y_pred2

    index2 += 1

# 2. calculate the error rate on the test set

test_err2 = (test_pred != y_test).sum()/y_test.shape[0]
print(f'\n test with K=2 Error:{test_err2}')

0.03333333333333333

 test with K=2 Error:0.06666666666666667


In [26]:
#4. model persistance (means save model for future use)

