# Lecture 8 Notes - KNN Implementation

Machine Learning steps
1. Data preparation
2. Model Training
3. Prediction and Evaluation
   - evalutation metric: % ofsamples missclassified
4. Model Persistance
   - how well it does in real world??

In [3]:
import numpy as np
from sklearn import datasets as ds # only imports some modules from sklearn. good because whole module may be too large
from sklearn.model_selection import train_test_split # split dataset into train and test sets

# data preparation
iris = ds.load_iris() #loading dataset on iris stuff
X = iris.data # feature vectors ie data
y = iris.target # classification of feature vectors in number format

print(X.shape, y.shape) # will give size of each vector
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2) # splits data set into a training set and test set
                                                                        # with corresponding target vectors

print(f"training set: {X_train.shape}, {y_train.shape}")
print(f"test set: {X_test.shape}, {y_test.shape}")

(150, 4) (150,)
training set: (120, 4), (120,)
test set: (30, 4), (30,)


In [ ]:
# model training
# KNN is an instance-based algorithm, and it does not have actual training

In [ ]:
# prediction and evaluation
# evaluation: error rate % of data samples missclassified

# prediction: 1) find K nearest neighbors 2) voting to predict

In [5]:
# find K nearest neighbors for an input data sample
def findKnNbs(x_star, X_train, K=5):
    """find K nearest neighbors for sample in the training set

    :param x_star: new data sample. Shape 1 by 4
    :param X_train: _description_

    return:
        K nearest neighbors' indeces
    """
    # calculate euclidean distance
    n = X_train.shape[0]
    dist = np.zeros((n,1)) # create numpy array of size n and init all val with 0
    
    index = 0
    for x in X_train:
        # d = ((x_star-x)*(x_star-x)).sum() # element wise multiplication
        d = np.sqrt(np.sum((x_star-x)*(x_star-x)))
        dist[index] = d
        index += 1
    
    # find k nearest neighbors using a sorting algo
    # numpy has sort!
    # print(dist)
    ind = np.argsort(dist, axis=0)
    # print(ind)
    # print(ind[:K]) # this slices up to the Kth element
    return ind[:K]

k_inx = findKnNbs(X_test[0], X_train)
print(k_inx)

[[22]
 [48]
 [23]
 [ 3]
 [31]]


In [18]:
# how to find euclidean distance
"""QUESTION
how does this translate to our samples? we're subtracting flower width, adding it to flower petal height, etc

is this how we should graph it then also?
"""
x_star = X_test[0]
print(x_star)

x = X_train[0]
print(x)

np.sqrt(np.sum((x_star-x)*(x_star-x)))

[5.  3.5 1.3 0.3]
[5.1 3.5 1.4 0.2]


0.17320508075688743

In [39]:
# prediction
# check the class lables of the k nns
k_labels = y_train[k_inx] # all 2's, which means the input sample will have label of 2
# print(k_labels) # matrix but we need a vector

counts = np.bincount(k_labels.reshape((5,)))
# print(counts)
y_pred = np.argmax(counts)
print(f"the prediction is {y_pred}")

[0 0 5]
the prediction is 2


In [11]:
# after class practice
# 1. how do we calculate the predictions for all test data samples
test_pred = np.zeros(X_test.shape[0])
index = 0
for i in X_test:
    ind = findKnNbs(i, X_train)

    i_labels = y_train[ind]
    counts = np.bincount(i_labels.reshape((5,)))
    y_pred = np.argmax(counts)
    test_pred[index] = y_pred

    index += 1

# 2. calculate the error rate on the test set

test_err = (test_pred != y_test).sum()/y_test.shape[0]
print(test_err)
# try to use different k

0.06666666666666667


In [ ]:
# model persistance